language: node_js
node_js:
  - 14
install:
  - npm install
  - yarn install
  - yarn devDB
  - yarn typeorm migration:run
script:
  - yarn test
env:
  global:
  - URL_MAIL=http://localhost:3333/answers